---
# tasks file for ansible-role-asterisk

- name: yum -y update
  yum:
    name: "*"
    state: present

# - name: yum group-install
#   yum:
#     name: ['@Development Tools']
#     state: present

- name: install requirements packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - libuuid-devel
#       - glibc-devel
#       - ncurses-devel
#       - openssl-devel
#       - zlib-devel
#       - sqlite-devel
#       - libxml2-devel

- name: git_clone
  git:
    repo: "https://github.com/asterisk/asterisk.git"
    dest: "{{ asterisk_src_dir }}"
    version: "{{ asterisk_version }}"
    force: yes
    update: yes

- name: asterisk install_prereq install
  command: chdir={{ asterisk_src_dir }}/contrib/scripts ./install_prereq install

- name: asterisk install_prereq install-unpackaged
  command: chdir={{ asterisk_src_dir }}/contrib/scripts ./install_prereq install-unpackaged

- name: comfigure asterisk
  command: chdir={{ asterisk_src_dir }} ./configure
