---
# tasks file for ansible-role-asterisk

- name: amzn2-core.repo priority down
  replace:
    path: /etc/yum.repos.d/amzn2-core.repo
    regexp: 'priority=10'
    replace: 'priority=99'
  when: ansible_facts['distribution'] == "Amazon"

- name: check exists EPEL
  shell: amazon-linux-extras list | grep epel
  register: epel_check
  failed_when: epel_check.rc not in [0,1]
  when: ansible_facts['distribution'] == "Amazon"

- name: install EPEL when amazon linux
  shell: amazon-linux-extras install -y epel
  when: ansible_facts['distribution'] == "Amazon" and epel_check.rc == 0

- name: amzn2-extras.repo priority down
  replace:
    path: /etc/yum.repos.d/amzn2-extras.repo
    regexp: 'priority = 10'
    replace: 'priority=99'
  when: ansible_facts['distribution'] == "Amazon"

- name: install EPEL when other linux
  yum:
    name: ['epel-release','https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm']
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: yum -y update
  yum:
    name: "*"
    state: present

- name: yum group-install
  yum:
    name: ['@Development Tools']
    state: present

- name: install requirements packages
  yum:
    name: "{{ packages }}"
    enablerepo: "epel"
  vars:
    packages:
      - libedit-devel
      # - jansson-devel # jansson 2.11が必要なのでソースからインストールする
      - libuuid-devel
      - sqlite-devel
      - libxml2-devel

- name: get jansson source file
  command: wget http://www.digip.org/jansson/releases/jansson-{{ jansson_version }}.tar.gz
  args:
    chdir: "{{ src_dir }}"
    warn: false

## janssonのソースインストールを解凍
- name: get jansson source file
  command: tar xvf jansson-{{ jansson_version }}.tar.gz
  args:
    chdir: "{{ src_dir }}"
    warn: false

- name: comfigure jansson
  command: ./configure
  args:
    chdir: "{{ jansson_src_dir }}"

- name: make jansson
  command: make
  args:
    chdir: "{{ jansson_src_dir }}"

- name: install jansson
  command: make install
  args:
    chdir: "{{ jansson_src_dir }}"

- name: git_clone asterisk
  git:
    repo: "https://github.com/asterisk/asterisk.git"
    dest: "{{ asterisk_src_dir }}"
    version: "{{ asterisk_version }}"
    force: yes
    update: yes

- name: asterisk install_prereq install
  command: ./install_prereq install
  args:
    chdir: "{{ asterisk_src_dir }}/contrib/scripts"
  when: ansible_facts['distribution'] == "CentOS"

- name: asterisk install_prereq install-unpackaged
  command: ./install_prereq install-unpackaged
  args:
    chdir: "{{ asterisk_src_dir }}/contrib/scripts"
  when: ansible_facts['distribution'] == "CentOS"

- name: comfigure asterisk
  command: ./configure
  args:
    chdir: "{{ asterisk_src_dir }}"

- name: make asterisk
  command: make
  args:
    chdir: "{{ asterisk_src_dir }}"

- name: make samples asterisk
  command: make samples
  args:
    chdir: "{{ asterisk_src_dir }}"

- name: touch /etc/redhat-release
  command: touch /etc/redhat-release
  args:
    warn: false
  when: ansible_facts['distribution'] == "Amazon"

- name: make config asterisk
  command: make config
  args:
    chdir: "{{ asterisk_src_dir }}"
