---
# tasks file for ansible-role-asterisk

- name: yum -y update
  yum:
    name: "*"
    state: present

- name: yum group-install
  yum:
    name: ['@Development Tools']
    state: present

- name: git_clone
  git:
    repo: "https://github.com/asterisk/asterisk.git"
    dest: "/usr/src/asterisk"
    version: "{{ asterisk_version }}"
    force: yes
    update: yes
