---
# tasks file for ansible-role-asterisk

- name: amzn2-core.repo priority down
  replace:
    path: /etc/yum.repos.d/amzn2-core.repo
    regexp: 'priority=10'
    replace: 'priority=99'
  when: ansible_facts['distribution'] == "Amazon"

- name: check exists EPEL
  shell: amazon-linux-extras list | grep epel
  register: epel_check
  failed_when: epel_check.rc not in [0,1]
  when: ansible_facts['distribution'] == "Amazon"

- name: install EPEL when amazon linux
  shell: amazon-linux-extras install -y epel
  when: ansible_facts['distribution'] == "Amazon" and epel_check.rc == 0

- name: amzn2-extras.repo priority down
  replace:
    path: /etc/yum.repos.d/amzn2-extras.repo
    regexp: 'priority = 10'
    replace: 'priority=99'
  when: ansible_facts['distribution'] == "Amazon"

- name: install EPEL when other linux
  yum:
    name: ['epel-release','https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm']
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: yum -y update
  yum:
    name: "*"
    state: present

- name: yum group-install
  yum:
    name: ['@Development Tools']
    state: present

- name: install requirements packages
  yum:
    name: "{{ packages }}"
    enablerepo: "epel"
  vars:
    packages:
      - libedit-devel
      # - jansson-devel # jansson 2.11が必要なのでソースからインストールする
      - libuuid-devel
      - sqlite-devel
      - libxml2-devel

- name: git_clone jansson 2.11
  git:
    repo: "https://github.com/akheron/jansson.git"
    dest: "{{ jansson_src_dir }}"
    version: "{{ jansson_version }}"
    force: yes
    update: yes

- name: comfigure jansson
  command: chdir={{ jansson_src_dir }} ./configure

- name: make jansson
  command: chdir={{ jansson_src_dir }} make

- name: install jansson
  command: chdir={{ jansson_src_dir }} make install

- name: git_clone asterisk
  git:
    repo: "https://github.com/asterisk/asterisk.git"
    dest: "{{ asterisk_src_dir }}"
    version: "{{ asterisk_version }}"
    force: yes
    update: yes

- name: asterisk install_prereq install
  command: chdir={{ asterisk_src_dir }}/contrib/scripts ./install_prereq install
  when: ansible_facts['distribution'] == "CentOS"

- name: asterisk install_prereq install-unpackaged
  command: chdir={{ asterisk_src_dir }}/contrib/scripts ./install_prereq install-unpackaged
  when: ansible_facts['distribution'] == "CentOS"

- name: comfigure asterisk
  command: chdir={{ asterisk_src_dir }} ./configure

- name: make asterisk
  command: chdir={{ asterisk_src_dir }} make

- name: install asterisk
  command: chdir={{ asterisk_src_dir }} make install
